# Generated by Django 3.2.7 on 2021-10-04 14:43

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbObject',
            fields=[
                ('userName', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('posts', djongo.models.fields.ArrayField(model_container=core.models.Post)),
            ],
        ),
        migrations.CreateModel(
            name='FbPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(max_length=100, unique=True)),
                ('userName', models.CharField(max_length=40)),
                ('userId', models.CharField(max_length=100)),
                ('postDescription', models.TextField(max_length=5000, null=True)),
                ('postImage', models.TextField(max_length=5000, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('postDescription', models.TextField(max_length=5000)),
                ('postImage', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
